#! /usr/local/bin/ruby

require 'colorize'

puts "your status:   ".white + "online".green

puts

puts "friends:"
puts "  matt(35)     ".white + "online".green
puts "  joel(2)      ".white + "offline".red
puts "  adam(18)     ".white + "offline".red
puts "  spencer(18)  ".white + "offline".red
